### ISSUE TITLE
May I ask what role the 100nF capacitor plays?

### ISSUE THREAD

**Issue by zwrr** [ChrisWIP/PS2AT#1]
Thanks for your design, I plan to make it, but I have a question, what role does the 100nF capacitor play? Under what circumstances do I need it.

**Comment by ChrisWIP** [comment]
Hi zwrr!

The capacitor is just a basic decoupler, and it's really just included for best practice. 

If you look at your motherboard you'll notice that every IC has a small (100nf or so) capacitor to do some decoupling, it provides a tiny amount of smoothing and reserve power as the device switches on and off rapidly.

The adapter will work fine without it as there will be decoupling in your keyboard. 😊

**Comment by zwrr** [comment]
Thanks for the answer, the PCB will be arriving soon, I will try to assemble it and use it.

**Comment by ChrisWIP** [comment]
Awesome! If you need any help shout out :)
